### ISSUE TITLE
turn off this lsp status!

### ISSUE THREAD

**Issue by ngtuonghy** [melkster/nvim#1]
![2023-03-18_19-04](https://user-images.githubusercontent.com/116539745/226104865-f7eccd1b-6767-4100-857e-0a35041c28c1.png)

hi i am using your source code as my nvim source code. so how to thi i am using your source code as my nvim source code. so how to turn off this lsp status!!

https://github.com/ngtuonghy/nvim.git

**Comment by mawkler** [comment]
@ngtuonghy If you're referring to the progress indicator in the bottom right, that is [fidget.nvim](https://github.com/j-hui/fidget.nvim). You can remove it simply by deleting [this line](https://github.com/mawkler/nvim/blob/7c42382174cd15cc76557a9c1dbc7ff3c9a1116b/init.lua#L58) from `init.lua`.

**Comment by ngtuonghy** [comment]
Thank you.  your source code is very good

**Comment by ngtuonghy** [comment]
> @ngtuonghyNếu bạn đang đề cập đến chỉ thông báo tiến trình ở bên dưới cùng bên phải, thì đó là [fidget.nvim](https://github.com/j-hui/fidget.nvim) . Bạn có thể xóa nó đơn giản bằng cách xóa [dòng này](https://github.com/mawkler/nvim/blob/7c42382174cd15cc76557a9c1dbc7ff3c9a1116b/init.lua#L58) khỏi tệp `init.lua`.

Thank you.  your source code is very good

**Comment by mawkler** [comment]
@ngtuonghy Thank you!
